### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by builderjer**
reverted back to single repo to maintain

several other improvements / changes

### CODE REVIEW

**Comment by Bulwagga** [comment]
Thanks...  Building the zip in a clean raspbian-lite 64 bit install gave me:

Done installing OVOS core

Installing systemd files

cp: cannot stat '/home/ovos/raspbian-ovos-rewrite/stage-core/02-messagebus/files/ovos-systemd-messagebus.service': No such file or directory
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting sdnotify
  Downloading https://www.piwheels.org/simple/sdnotify/sdnotify-0.3.2-py3-none-any.whl (3.5 kB)
Installing collected packages: sdnotify
Successfully installed sdnotify-0.3.2

Enabling service files

**Comment by builderjer** [comment]
fixed

`git pull`

**Comment by Bulwagga** [comment]
Problems around /ramdisk... 
Jul  2 14:02:29 raspOvos ovos-systemd-messagebus[7619]: Traceback (most recent call last):
Jul  2 14:02:29 raspOvos ovos-systemd-messagebus[7619]:   File "/home/ovos/.local/bin/ovos-systemd-messagebus", line 18, in <module>
Jul  2 14:02:29 raspOvos ovos-systemd-messagebus[7619]:     from mycroft.messagebus.service.__main__ import main
Jul  2 14:02:29 raspOvos ovos-systemd-messagebus[7619]:   File "/home/ovos/.local/lib/python3.9/site-packages/mycroft/__init__.py", line 37, in <module>
Jul  2 14:02:29 raspOvos ovos-systemd-messagebus[7619]:     LOG.warning("mycroft has been deprecated! please start importing from ovos_core and companion pa>
Jul  2 14:02:29 raspOvos ovos-systemd-messagebus[7619]:   File "/home/ovos/.local/lib/python3.9/site-packages/ovos_utils/log.py", line 148, in warning
Jul  2 14:02:29 raspOvos ovos-systemd-messagebus[7619]:     cls._get_real_logger().warning(*args, **kwargs)
Jul  2 14:02:29 raspOvos ovos-systemd-messagebus[7619]:   File "/home/ovos/.local/lib/python3.9/site-packages/ovos_utils/log.py", line 127, in _get_real_log>
Jul  2 14:02:29 raspOvos ovos-systemd-messagebus[7619]:     logger = cls.create_logger(name, tostdout=True)
Jul  2 14:02:29 raspOvos ovos-systemd-messagebus[7619]:   File "/home/ovos/.local/lib/python3.9/site-packages/ovos_utils/log.py", line 87, in create_logger
Jul  2 14:02:29 raspOvos ovos-systemd-messagebus[7619]:     os.makedirs(cls.base_path, exist_ok=True)
Jul  2 14:02:29 raspOvos ovos-systemd-messagebus[7619]:   File "/usr/lib/python3.9/os.py", line 215, in makedirs
Jul  2 14:02:29 raspOvos ovos-systemd-messagebus[7619]:     makedirs(head, exist_ok=exist_ok)
Jul  2 14:02:29 raspOvos ovos-systemd-messagebus[7619]:   File "/usr/lib/python3.9/os.py", line 225, in makedirs
Jul  2 14:02:29 raspOvos ovos-systemd-messagebus[7619]:     mkdir(name, mode)
Jul  2 14:02:29 raspOvos ovos-systemd-messagebus[7619]: PermissionError: [Errno 13] Permission denied: '/ramdisk'
Jul  2 14:02:30 raspOvos systemd[507]: ovos-messagebus.service: Main process exited, code=exited, status=1/FAILURE
Jul  2 14:02:30 raspOvos systemd[507]: ovos-messagebus.service: Failed with result 'exit-code'.
Jul  2 14:02:30 raspOvos systemd[507]: Failed to start OVOS Messagebus.
Jul  2

**Comment by Bulwagga** [comment]
sudo mkdir /ramdisk/
sudo chmod ugo+rwx /ramdisk

did the trick. the errors after seem to be OVOS configuration issues.  I will pull and re-install periodically.

**Comment by builderjer** [comment]
sorry, I didn't see this till now.  we can remove the `/ramdisk` logs from `mycroft.conf` or create a ramdisk in the `manual_user_install.sh` script.  I think that just commenting them out of the config, with a comment saying why will work.

give me a few

**Comment by builderjer** [comment]
@Bulwagga give it a shot now

**Comment by Bulwagga** [comment]
No worries. Please dont feel any pressure from me.  We are troubleshooting a freezer issue here. You're doing a great job!  I'm really excited to see those servers come online.+}
-------- Original message --------From: builderjer ***@***.***> Date: 7/2/23  9:56 PM  (GMT-05:00) To: OpenVoiceOS/raspbian-ovos ***@***.***> Cc: Bulwagga ***@***.***>, Comment ***@***.***> Subject: Re: [OpenVoiceOS/raspbian-ovos] Rewrite (PR #61) 
sorry, I didn't see this till now.  we can remove the /ramdisk logs from mycroft.conf or create a ramdisk in the manual_user_install.sh script.  I think that just commenting them out of the config, with a comment saying why will work.
give me a few

**Comment by Bulwagga** [comment]
Any reason I can't go ahead and delete my Bulwagga/raspbian-ovos repository?  I'm thinking of keeping things as simple as possible..

**Comment by builderjer** [comment]
You could keep it, and keep contributing. But if you want to delete it, there is no reason you can't

**Comment by builderjer** [comment]
I would like to see an option to install the Gui In the manual install  script  eventually

**Comment by Bulwagga** [comment]
Do the contents of the stage-* file trees contain enough information to create the manual_user_install.sh script automatically? I'm assuming you run a script on the contents of raspbian-ovos and it creates the image file as specified in raspbian-ovos-config... where could I find this script (or program)? Thanks!

**Comment by builderjer** [comment]
short answer, no, I do not think so

explanation:

So the RPi foundation has a script for building images called [pi-gen](https://github.com/RPi-Distro/pi-gen).  With that, run by itself, you can build a vanilla raspberryPiOS-lite or full image, and even a noobs image.  What this repo does is takes the first few stages from that, which builds a minimal "lite" image, and extends that to have ovos installed as the OS instead of raspbian.  When this first started, all of this was in a single stage, and just installed the pip files.  It has grown into what it is now in just a few months.  the `raspbian-ovos-config` file will be, or already is removed from the latest.  It is/was there so that there was a config file to follow to build your own complete image.  you can look at [this file](https://github.com/OpenVoiceOS/raspbian-ovos/blob/dev/.github/workflows/raspbian-ovos.yaml) for how it is processing the stages for the official build.  I have tried to separate the stages into what is happening, mainly to make debugging easier.  On a local build, you can skip stages that have already been built correctly and continue with debugging from there.

`manual_user_install.sh` script:
This was put there originally so something was there while I created the stages to build an image.  It was never actually meant to stay and be used, but I have found that several people use it.  SOOOOOO, this is what I would like it to become.

Not sure how long you have used mycroft/ovos/neon, but the original `mycroft-cor` had a [dev_setup.sh](https://github.com/MycroftAI/mycroft-core/blob/dev/dev_setup.sh) script that would setup mycroft on your device for you and try to detect the OS that is being used.  I would like something like this as a final step for this script.

Wanna help?

p.s.  you should really join the matrix channels. communicating is easier, and you can see a whole bunch of development going on.  https://matrix.to/#/#openvoiceos-support:matrix.org  https://matrix.to/#/#openvoiceos-general:matrix.org  https://matrix.to/#/#openvoiceos-development:matrix.org

**Comment by Bulwagga** [comment]
Yeah, I'm interested in helping. I've been watching matrix for a few weeks to get the flow.  I'm interested in helping, but my relevant skill level tops out with script building. I fully support  your vision for creating something similar to dev_setup.sh for OVOS.  I have several RPi devices doing multiple tasks, and the value I see is using a PC as a tts/stt server and having the pi's continuing to do their tasks while listening for wake words. I ran mycroft on two Ubuntu PCs starting with dev_setup.sh. Having one script supporting multiple OSs seems like the way to go.  My only doubt about the concept is that if OVOS as an OS works decently enough on the PIi, there won't be much demand for client software on desktops. But that is a ways in the future.  For now I'm trying to simply get the script current with the newly merged environment. Thanks for the encouragement.  Please suggest things as you think of them and I'll do my best to stay oriented in a useful direction.

**Pull request merged**
